---
- name: Import GPG key
  rpm_key:
    state: present
    key: http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key

- name: Create jenkins repository
  yum_repository:
    name: jenkins
    description: Jenkins Repository
    baseurl: http://pkg.jenkins.io/redhat
    enabled: yes
    gpgcheck: yes

- name: Install Java 8
  yum:
    name: java-1.8.0-openjdk.x86_64
    state: present

- name: Install Git
  yum:
    name: git
    state: present

- name: Set Java 8 as default
  command: /usr/sbin/alternatives --set java /usr/lib/jvm/jre-1.8.0-openjdk.x86_64/bin/java

- name: Install Jenkins
  yum:
    name: jenkins
    state: present

- name: Start the Jenkins service and enable it on restart
  service:
    name: jenkins
    state: started
    enabled: yes
